config/routes.rb
Rails.application.routes.draw do

  get 'welcome/index'
  root 'welcome#index'
  resources :articles do
    resources :comments
  end

end

app/models/article.rb
class Article < ActiveRecord::Base
  has_many :comments,dependent: :destroy
  validates :title, presence: true, length: {minimum:3}
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :first_name,
            presence: true
  validates :last_name,
            presence: true
  validates :email,
            presence: true,
            uniqueness: true,
            format: {
              with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
            }
  def to_s
    "#{first_name} #{last_name}"
end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def edit
    @article = Article.find(params[:id])
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to @article
  end

    private
    def article_params
      params.require(:article).permit(:title, :text)
    end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article)
  end

  private
    def comment_params
      params.require(:comment).permit(:commenter,:body)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>

  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group col-xs-3">
    <label for="title">Title<br></label>
    <input type="text" class="form-control" name="article[title]"></input>
  </div>

  <div class="form-group col-xs-3">
    <label for="title">Text<br></label>
    <input type="text" class="form-control" name="article[text]"></input>
  </div>
  <!-- <div class="form-group">
    <button type="button" class="btn btn-primary" name="article[submit]">Submit</button>
  </div> -->

  <p>
    <%= f.submit :Submit, class: 'btn btn-primary' %>
  </p>

<% end %>

app/views/articles/edit.html.erb
<div class="container">
  <h1>Editing article</h1>
  <%= render 'form' %>
  <%= link_to 'Back', articles_path %>

</div>

app/views/articles/index.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <div class="container">
      <h1>Listing Articles</h1>
      <button type="button" class="btn btn-primary"style="margin-bottom: 30px;margin-top: 15px;"><a href="/articles/new" style="color: white;">Add New</a></button>

      <table class="table table-striped">
        <tr>
          <th>Title</th>
          <th>Text</th>
          <th></th>
        </tr>
        <% @articles.each do |article| %>
          <tr>
            <td><%= article.title %></td>
            <td><%= article.text %></td>
            <td><%= link_to 'Show', article_path(article) %></td>
            <td><%= link_to 'Edit', edit_article_path(article) %></td>
            <td><%= link_to 'Destroy', article_path(article),method: :delete,data: {confirm: 'Are you sure?'} %></td>
          </tr>
        <% end %>
      </table>
    </div>
  </body>
</html>

app/views/articles/new.html.erb
<div class="container">
  <h1>New Article</h1>
  <%= render 'form' %>
  <%= link_to 'Back', articles_path %>

</div>

app/views/articles/show.html.erb
<div class="container">
  <p>
    <strong>Title:</strong>
    <%= @article.title %>
  </p>

  <p>
    <strong>Text:</strong>
    <%= @article.text %>
  </p>

  <!-- existing comments -->
  <h2>Comments</h2>
  <%= render @article.comments %>

  <!-- adding comment -->
  <h2>Add a comment:</h2>
  <%= render 'comments/form' %>

  <%= link_to 'Edit', edit_article_path(@article) %> |
  <%= link_to 'Back', articles_path %>

</div>

app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>

<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>

<p>
  <%= link_to 'Destroy Comment', [comment.article, comment],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
</p>

app/views/comments/_form.html.erb
<%= form_for([@article, @article.comments.build]) do |f| %>
  <p>
    <%= f.label :commenter %><br>
    <%= f.text_field :commenter %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/welcome/index.html.erb
<h1>Hello, Rails!</h1>
<%= link_to 'My Blog', controller: 'articles' %>
<%= link_to 'Add New', new_article_path %>